---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - ../../defaults/main.yml
  #vars:


  tasks:
    - name: "Include ansible_role_selinux"
      include_role:
        name: "ansible_role_selinux"

  #roles:
    #- role: habbis.ansible_role_selinux
